### ISSUE TITLE
How to load nm.el at Emacs startup.

### ISSUE THREAD

**Issue by jherrlin** [Kodkollektivet/emacs-nm#2]
How do we load the file at Emacs startup to make it available via `M-x`?

**Comment by jherrlin** [comment]
I found a way to do this with `cask`

In `Cask` file:

```emacs-lisp
(depends-on "emacs-nm" :git "https://github.com/kodkollektivet/emacs-nm.git")
```

In 'init.el' file:

```emacs-lisp
(require 'nm)
```

**Comment by rasjostrom** [comment]
It can also be required as long as nm.el is placed anywhere on your loadpath because of the `provide`!
