### ISSUE TITLE
Password Is Not Masked

### ISSUE THREAD

**Issue by abbreviatedman** [Kodkollektivet/emacs-nm#9]
When running `nm/connect-basic`, `read-string` is used to read the password, which fails to mask the password the user is entering.

If we used `password-read` instead, it should solve this problem.

I have a branch ready to PR if this sounds like a reasonable fix!

**Comment by jherrlin** [comment]
That sound like the way to do it. Please submit a PR if you want, would really appreciate it!

**Comment by jherrlin** [comment]
Thank you for the PR!
